/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import grafoLista.Amizade;
import grafoLista.GrafoListaSocial;
import grafoLista.Pessoa;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maico
 */
public class Telas extends javax.swing.JFrame {

    private static GrafoListaSocial listaSocial;
    private Pessoa logada;
    private static ArrayList<Pessoa> nAmigos;
    private static ArrayList<Pessoa> seguidores;

    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
        listaSocial = new GrafoListaSocial();
        seguidores = new ArrayList<>();
        logada = new Pessoa();

    }

    private void perfilLogado(Pessoa pessoa) {
        logada = pessoa;
        jLabelPerfilNome.setText(logada.getNome());
        jLabelPerfilEmail.setText(logada.getEmail());
        jLabelPerfilNascimento.setText(logada.getNascnimento());
    }

    private void mostraCard(String cardName) {
        CardLayout card = (CardLayout) jTetaPrincipal.getLayout();
        card.show(jTetaPrincipal, cardName);
    }

    private void limpaCadastro() {
        jTextFieldCadastroNome.setText("");
        jTextFieldCadastroEmail.setText("");
        jFormattedTextFieldDataNasc.setText("00-00-00");
    }

    private void atualizaAmigos() {

        DefaultTableModel modeloTabela = (DefaultTableModel) jTableAmigos.getModel();
        modeloTabela.setNumRows(0);
        for (Amizade amizade : logada.getAmizades()) {
            modeloTabela.addRow(new Object[]{
                amizade.getDestino().getNome()
            });
        }
    }

    private void atualizaSeguidores() {
        seguidores = new ArrayList<>();

        for (Pessoa pessoa : listaSocial.getPessoas()) {
            for(Amizade amizade: pessoa.getAmizades()) {
                if(amizade.getDestino().equals(logada))
                seguidores.add(pessoa);
            }
        }
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableSeguidores.getModel();
        modeloTabela.setNumRows(0);
        for (Pessoa pessoa : seguidores) {
            modeloTabela.addRow(new Object[]{
                pessoa.getNome()
            });
        }
    }

    private void atualizaNovosAMigos() {
        nAmigos = new ArrayList<>();

        for (Pessoa pessoa : listaSocial.getPessoas()) {
            nAmigos.add(pessoa);
        }
        nAmigos.remove(logada);
        for (Amizade amizade : logada.getAmizades()) {
            if (nAmigos.contains(amizade.getDestino())) {
                nAmigos.remove(amizade.getDestino());
            }
        }
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableNovosAmigos1.getModel();
        modeloTabela.setNumRows(0);
        for (Pessoa pessoa : nAmigos) {
            if (pessoa != logada) {
                modeloTabela.addRow(new Object[]{
                    pessoa.getNome()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTetaPrincipal = new javax.swing.JPanel();
        jTelaLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldLoginEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastro = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelAvisoLogin = new javax.swing.JLabel();
        jTelaCadastro = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jTextFieldCadastroNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jButtonCadastrar3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jButtonSairCadastro = new javax.swing.JButton();
        jTelaPerfil = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelPerfilNome = new javax.swing.JLabel();
        jLabelPerfilEmail = new javax.swing.JLabel();
        jLabelPerfilNascimento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonLogaut = new javax.swing.JButton();
        jButtonAmigos = new javax.swing.JButton();
        Seguidores = new javax.swing.JButton();
        jTelaAmigos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonMeuPerfil = new javax.swing.JButton();
        jButtonNovosAmigos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAmigos = new javax.swing.JTable();
        jTelaNovosAmigos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonMeuPerfil1 = new javax.swing.JButton();
        jButtonAdicionarAmigos1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNovosAmigos1 = new javax.swing.JTable();
        jTelaSeguidores = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonMeuPerfil2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSeguidores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTetaPrincipal.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldLoginEmail.setColumns(5);
        jTextFieldLoginEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 49, 263, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 52, -1, -1));

        jButtonCadastro.setText("Cadastrar");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, -1));

        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 90, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("OU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 24));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 6, -1, -1));

        jLabelAvisoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvisoLogin.setText("       ");
        jPanel1.add(jLabelAvisoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 84, 263, -1));

        javax.swing.GroupLayout jTelaLoginLayout = new javax.swing.GroupLayout(jTelaLogin);
        jTelaLogin.setLayout(jTelaLoginLayout);
        jTelaLoginLayout.setHorizontalGroup(
            jTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaLoginLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTelaLoginLayout.setVerticalGroup(
            jTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTetaPrincipal.add(jTelaLogin, "jTelaLogin");

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 255));
        jLabel18.setText("Data de Nascimento:");

        jFormattedTextFieldDataNasc.setColumns(5);
        jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-y"))));

        jTextFieldCadastroNome.setColumns(20);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Nome:");

        jTextFieldCadastroEmail.setColumns(20);

        jButtonCadastrar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastrar3.setText("Cadastrar");
        jButtonCadastrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 255));
        jLabel16.setText("Cadastrar");

        jLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(51, 204, 255));
        jLabel.setText("Email:");

        jButtonSairCadastro.setText("Sair");
        jButtonSairCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel4)
                            .addComponent(jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jButtonCadastrar3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButtonSairCadastro)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel))
                .addGap(31, 31, 31)
                .addComponent(jButtonCadastrar3)
                .addGap(18, 18, 18)
                .addComponent(jButtonSairCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTelaCadastroLayout = new javax.swing.GroupLayout(jTelaCadastro);
        jTelaCadastro.setLayout(jTelaCadastroLayout);
        jTelaCadastroLayout.setHorizontalGroup(
            jTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaCadastroLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jTelaCadastroLayout.setVerticalGroup(
            jTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaCadastroLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTetaPrincipal.add(jTelaCadastro, "jTelaCadastro");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 110));

        jLabelPerfilNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPerfilNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilNome.setText("Fulano");
        jPanel4.add(jLabelPerfilNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, -1));

        jLabelPerfilEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPerfilEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilEmail.setText("Email@email.com");
        jLabelPerfilEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelPerfilEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabelPerfilEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 320, -1));
        jLabelPerfilEmail.getAccessibleContext().setAccessibleDescription("Email@email.com");

        jLabelPerfilNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPerfilNascimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilNascimento.setText("Nascido em:");
        jPanel4.add(jLabelPerfilNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Perfil");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jButtonLogaut.setText("Logaut");
        jButtonLogaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogautActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonLogaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonAmigos.setText("Voce Segui");
        jButtonAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmigosActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAmigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));

        Seguidores.setText("Seguidores");
        Seguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguidoresActionPerformed(evt);
            }
        });
        jPanel4.add(Seguidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        javax.swing.GroupLayout jTelaPerfilLayout = new javax.swing.GroupLayout(jTelaPerfil);
        jTelaPerfil.setLayout(jTelaPerfilLayout);
        jTelaPerfilLayout.setHorizontalGroup(
            jTelaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTelaPerfilLayout.setVerticalGroup(
            jTelaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTetaPrincipal.add(jTelaPerfil, "jTelaPerfil");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeuPerfil.setText("Meu Perfil");
        jButtonMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMeuPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonNovosAmigos.setText("Seguir mais Pessoas");
        jButtonNovosAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovosAmigosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNovosAmigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 140, -1));

        jTableAmigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Voce Segue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAmigosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAmigos);
        if (jTableAmigos.getColumnModel().getColumnCount() > 0) {
            jTableAmigos.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 420));

        javax.swing.GroupLayout jTelaAmigosLayout = new javax.swing.GroupLayout(jTelaAmigos);
        jTelaAmigos.setLayout(jTelaAmigosLayout);
        jTelaAmigosLayout.setHorizontalGroup(
            jTelaAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaAmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTelaAmigosLayout.setVerticalGroup(
            jTelaAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaAmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTetaPrincipal.add(jTelaAmigos, "jTelaAmigos");

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeuPerfil1.setText("Meu Perfil");
        jButtonMeuPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfil1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonMeuPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        jButtonAdicionarAmigos1.setText("Seguir");
        jButtonAdicionarAmigos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAmigos1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAdicionarAmigos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 70, -1));

        jTableNovosAmigos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pessoas para seguir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNovosAmigos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNovosAmigos1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableNovosAmigos1);
        if (jTableNovosAmigos1.getColumnModel().getColumnCount() > 0) {
            jTableNovosAmigos1.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 280));

        javax.swing.GroupLayout jTelaNovosAmigosLayout = new javax.swing.GroupLayout(jTelaNovosAmigos);
        jTelaNovosAmigos.setLayout(jTelaNovosAmigosLayout);
        jTelaNovosAmigosLayout.setHorizontalGroup(
            jTelaNovosAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaNovosAmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTelaNovosAmigosLayout.setVerticalGroup(
            jTelaNovosAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaNovosAmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTetaPrincipal.add(jTelaNovosAmigos, "jTelaNovosAmigos");

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeuPerfil2.setText("Meu Perfil");
        jButtonMeuPerfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfil2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonMeuPerfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        jTableSeguidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Seguidores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSeguidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSeguidoresMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableSeguidores);
        if (jTableSeguidores.getColumnModel().getColumnCount() > 0) {
            jTableSeguidores.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 280));

        javax.swing.GroupLayout jTelaSeguidoresLayout = new javax.swing.GroupLayout(jTelaSeguidores);
        jTelaSeguidores.setLayout(jTelaSeguidoresLayout);
        jTelaSeguidoresLayout.setHorizontalGroup(
            jTelaSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaSeguidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTelaSeguidoresLayout.setVerticalGroup(
            jTelaSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaSeguidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTetaPrincipal.add(jTelaSeguidores, "jTelaSeguidores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTetaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTetaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed

        limpaCadastro();
        jLabelAvisoLogin.setText("");
        mostraCard("jTelaCadastro");

    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
            Pessoa pessoa = listaSocial.getPessoaPorEmail(jTextFieldLoginEmail.getText());
            perfilLogado(pessoa);
            atualizaAmigos();
            mostraCard("jTelaPerfil");
        } catch (Exception e) {
            jLabelAvisoLogin.setText("Email nao encontrado");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonCadastrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar3ActionPerformed

        Pessoa pessoa = new Pessoa(
                jTextFieldCadastroNome.getText(),
                jTextFieldCadastroEmail.getText(),
                jFormattedTextFieldDataNasc.getText());
        listaSocial.adicionarPessoa(pessoa);
        listaSocial.getPessoaPorNome(jTextFieldCadastroNome.getText());
        mostraCard("jTelaLogin");
        jTextFieldLoginEmail.setText(jTextFieldCadastroEmail.getText());
        limpaCadastro();
        jLabelAvisoLogin.setText("");

    }//GEN-LAST:event_jButtonCadastrar3ActionPerformed

    private void jButtonLogautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogautActionPerformed
        mostraCard("jTelaLogin");
        jLabelAvisoLogin.setText("");

    }//GEN-LAST:event_jButtonLogautActionPerformed

    private void jButtonSairCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadastroActionPerformed
        mostraCard("jTelaLogin");
        limpaCadastro();
        jLabelAvisoLogin.setText("");

    }//GEN-LAST:event_jButtonSairCadastroActionPerformed

    private void jButtonAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmigosActionPerformed
        atualizaAmigos();
        mostraCard("jTelaAmigos");
    }//GEN-LAST:event_jButtonAmigosActionPerformed

    private void jTableAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAmigosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableAmigosMouseClicked

    private void jButtonMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfilActionPerformed
        mostraCard("jTelaPerfil");
        atualizaAmigos();
    }//GEN-LAST:event_jButtonMeuPerfilActionPerformed

    private void jButtonNovosAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovosAmigosActionPerformed
        mostraCard("jTelaNovosAmigos");
        atualizaNovosAMigos();
        jButtonAdicionarAmigos1.setVisible(false);
    }//GEN-LAST:event_jButtonNovosAmigosActionPerformed

    private void jButtonMeuPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfil1ActionPerformed
        mostraCard("jTelaPerfil");
        atualizaAmigos();
    }//GEN-LAST:event_jButtonMeuPerfil1ActionPerformed

    private void jButtonAdicionarAmigos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmigos1ActionPerformed
        try {

            Pessoa pessoa = nAmigos.get(jTableNovosAmigos1.getSelectedRow());
            int opc = JOptionPane.showConfirmDialog(null,
                    "Adicionar " + pessoa.getNome()
                    + " email" + pessoa.getEmail() + "?");
            if (opc == JOptionPane.YES_OPTION) {
                Pessoa aux = logada;
                logada.adicionarAmizade(pessoa);
                listaSocial.atualizaPessoa(aux, logada);
                atualizaNovosAMigos();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonAdicionarAmigos1ActionPerformed

    private void jTableNovosAmigos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNovosAmigos1MouseClicked
        jButtonAdicionarAmigos1.setVisible(true);
    }//GEN-LAST:event_jTableNovosAmigos1MouseClicked

    private void SeguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguidoresActionPerformed
        mostraCard("jTelaSeguidores");
        atualizaSeguidores();
    }//GEN-LAST:event_SeguidoresActionPerformed

    private void jButtonMeuPerfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfil2ActionPerformed
        mostraCard("jTelaPerfil");
        atualizaAmigos();
    }//GEN-LAST:event_jButtonMeuPerfil2ActionPerformed

    private void jTableSeguidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSeguidoresMouseClicked

    }//GEN-LAST:event_jTableSeguidoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Seguidores;
    private javax.swing.JButton jButtonAdicionarAmigos1;
    private javax.swing.JButton jButtonAmigos;
    private javax.swing.JButton jButtonCadastrar3;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonLogaut;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonMeuPerfil;
    private javax.swing.JButton jButtonMeuPerfil1;
    private javax.swing.JButton jButtonMeuPerfil2;
    private javax.swing.JButton jButtonNovosAmigos;
    private javax.swing.JButton jButtonSairCadastro;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAvisoLogin;
    private javax.swing.JLabel jLabelPerfilEmail;
    private javax.swing.JLabel jLabelPerfilNascimento;
    private javax.swing.JLabel jLabelPerfilNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableAmigos;
    private javax.swing.JTable jTableNovosAmigos1;
    private javax.swing.JTable jTableSeguidores;
    private javax.swing.JPanel jTelaAmigos;
    private javax.swing.JPanel jTelaCadastro;
    private javax.swing.JPanel jTelaLogin;
    private javax.swing.JPanel jTelaNovosAmigos;
    private javax.swing.JPanel jTelaPerfil;
    private javax.swing.JPanel jTelaSeguidores;
    private javax.swing.JPanel jTetaPrincipal;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldCadastroNome;
    private javax.swing.JTextField jTextFieldLoginEmail;
    // End of variables declaration//GEN-END:variables
}
