/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import grafoLista.GrafoListaSocial;
import grafoLista.Pessoa;
import grafoLista.Seguindo;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maico
 */
public class Telas extends javax.swing.JFrame {

    private static GrafoListaSocial listaSocial;
    private Pessoa logada;
    private static ArrayList<Pessoa> nSeguindo;
    private static ArrayList<Pessoa> seguidores;
    private static ArrayList<Pessoa> seguindo;

    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
        listaSocial = new GrafoListaSocial();
        seguidores = new ArrayList<>();
        logada = new Pessoa();

    }

    private void perfilLogado(Pessoa pessoa) {
        logada = pessoa;
        jLabelPerfilNome.setText(logada.getNome());
        jLabelPerfilEmail.setText(logada.getEmail());
        jLabelPerfilNascimento.setText(logada.getNascnimento());
    }

    private void mostraCard(String cardName) {
        CardLayout card = (CardLayout) jTetaPrincipal.getLayout();
        card.show(jTetaPrincipal, cardName);
    }

    private void limpaCadastro() {
        jTextFieldCadastroNome.setText("");
        jTextFieldCadastroEmail.setText("");
        jFormattedTextFieldDataNasc.setText("00-00-00");
    }

    private void atualizaSeguindo() {
        seguindo = new ArrayList<>();
        jButtonPararDeSeguir.setVisible(false);
        for (Seguindo s : logada.getSeguindo()) {
            seguindo.add(s.getDestino());
        }
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableSeguindo.getModel();
        modeloTabela.setNumRows(0);
        for (Pessoa p : seguindo) {
            modeloTabela.addRow(new Object[]{
                p.getNome()
            });
        }
    }

    private void atualizaSeguidores() {
        seguidores = new ArrayList<>();

        for (Pessoa pessoa : listaSocial.getPessoas()) {
            for (Seguindo s : pessoa.getSeguindo()) {
                if (s.getDestino().equals(logada)) {
                    seguidores.add(pessoa);
                }
            }
        }
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableSeguidores.getModel();
        modeloTabela.setNumRows(0);
        for (Pessoa pessoa : seguidores) {
            modeloTabela.addRow(new Object[]{
                pessoa.getNome()
            });
        }
    }

    private void atualizaNovosSeguindo() {
        nSeguindo = new ArrayList<>();

        for (Pessoa pessoa : listaSocial.getPessoas()) {
            nSeguindo.add(pessoa);
        }
        nSeguindo.remove(logada);
        for (Seguindo s : logada.getSeguindo()) {
            if (nSeguindo.contains(s.getDestino())) {
                nSeguindo.remove(s.getDestino());
            }
        }
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableNovosSeguindo.getModel();
        modeloTabela.setNumRows(0);
        for (Pessoa pessoa : nSeguindo) {
            if (pessoa != logada) {
                modeloTabela.addRow(new Object[]{
                    pessoa.getNome()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTetaPrincipal = new javax.swing.JPanel();
        jTelaLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldLoginEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastro = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelAvisoLogin = new javax.swing.JLabel();
        jTelaCadastro = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jTextFieldCadastroNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jButtonCadastrar3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jButtonSairCadastro = new javax.swing.JButton();
        jLabelCadastroNotifica = new javax.swing.JLabel();
        jTelaPerfil = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelPerfilNome = new javax.swing.JLabel();
        jLabelPerfilEmail = new javax.swing.JLabel();
        jLabelPerfilNascimento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonLogaut = new javax.swing.JButton();
        jButtonSeguindo = new javax.swing.JButton();
        Seguidores = new javax.swing.JButton();
        jTelaSeguindo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonMeuPerfil = new javax.swing.JButton();
        jButtonSeguirNovos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSeguindo = new javax.swing.JTable();
        jButtonPararDeSeguir = new javax.swing.JButton();
        jTelaNovosSeguindo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonMeuPerfil1 = new javax.swing.JButton();
        jButtonSeguir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNovosSeguindo = new javax.swing.JTable();
        jTelaSeguidores = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonMeuPerfil2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSeguidores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTetaPrincipal.setLayout(new java.awt.CardLayout(1, 0));

        jTelaLogin.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldLoginEmail.setColumns(5);
        jTextFieldLoginEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 263, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 30));

        jButtonCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastro.setText("Cadastrar");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, -1));

        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, -1));

        jLabelAvisoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvisoLogin.setText("       ");
        jPanel1.add(jLabelAvisoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 263, -1));

        javax.swing.GroupLayout jTelaLoginLayout = new javax.swing.GroupLayout(jTelaLogin);
        jTelaLogin.setLayout(jTelaLoginLayout);
        jTelaLoginLayout.setHorizontalGroup(
            jTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaLoginLayout.setVerticalGroup(
            jTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        jTetaPrincipal.add(jTelaLogin, "jTelaLogin");

        jTelaCadastro.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 255));
        jLabel18.setText("Dt. Nasc:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, -1));

        jFormattedTextFieldDataNasc.setColumns(5);
        jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-y"))));
        jPanel3.add(jFormattedTextFieldDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 240, -1));

        jTextFieldCadastroNome.setColumns(20);
        jPanel3.add(jTextFieldCadastroNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Nome:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jTextFieldCadastroEmail.setColumns(20);
        jPanel3.add(jTextFieldCadastroEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, -1));

        jButtonCadastrar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastrar3.setText("Cadastrar");
        jButtonCadastrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrar3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCadastrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 255));
        jLabel16.setText("Cadastrar");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(51, 204, 255));
        jLabel.setText("Email:");
        jPanel3.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jButtonSairCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSairCadastro.setText("Sair");
        jButtonSairCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadastroActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSairCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabelCadastroNotifica.setText("   ");
        jPanel3.add(jLabelCadastroNotifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        javax.swing.GroupLayout jTelaCadastroLayout = new javax.swing.GroupLayout(jTelaCadastro);
        jTelaCadastro.setLayout(jTelaCadastroLayout);
        jTelaCadastroLayout.setHorizontalGroup(
            jTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaCadastroLayout.setVerticalGroup(
            jTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        jTetaPrincipal.add(jTelaCadastro, "jTelaCadastro");

        jTelaPerfil.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 140, 90));

        jLabelPerfilNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPerfilNome.setForeground(new java.awt.Color(51, 255, 255));
        jLabelPerfilNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilNome.setText("Fulano");
        jPanel4.add(jLabelPerfilNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 320, -1));

        jLabelPerfilEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPerfilEmail.setForeground(new java.awt.Color(0, 255, 255));
        jLabelPerfilEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilEmail.setText("Email@email.com");
        jLabelPerfilEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelPerfilEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabelPerfilEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 320, -1));
        jLabelPerfilEmail.getAccessibleContext().setAccessibleDescription("Email@email.com");

        jLabelPerfilNascimento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPerfilNascimento.setForeground(new java.awt.Color(51, 255, 255));
        jLabelPerfilNascimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerfilNascimento.setText("Nascido em:");
        jPanel4.add(jLabelPerfilNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 250, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Perfil");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jButtonLogaut.setText("Logout");
        jButtonLogaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogautActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonLogaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonSeguindo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSeguindo.setText("Seguindo");
        jButtonSeguindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeguindoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSeguindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 110, -1));

        Seguidores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Seguidores.setText("Seguidores");
        Seguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguidoresActionPerformed(evt);
            }
        });
        jPanel4.add(Seguidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        javax.swing.GroupLayout jTelaPerfilLayout = new javax.swing.GroupLayout(jTelaPerfil);
        jTelaPerfil.setLayout(jTelaPerfilLayout);
        jTelaPerfilLayout.setHorizontalGroup(
            jTelaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaPerfilLayout.setVerticalGroup(
            jTelaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        jTetaPrincipal.add(jTelaPerfil, "jTelaPerfil");

        jTelaSeguindo.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(460, 363));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeuPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMeuPerfil.setText("Meu Perfil");
        jButtonMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonMeuPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButtonSeguirNovos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSeguirNovos.setText("Seguir mais Pessoas");
        jButtonSeguirNovos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeguirNovosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSeguirNovos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 170, -1));

        jTableSeguindo.setBackground(new java.awt.Color(153, 153, 153));
        jTableSeguindo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableSeguindo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Seguindo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSeguindo.setGridColor(new java.awt.Color(0, 0, 0));
        jTableSeguindo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSeguindoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSeguindo);
        if (jTableSeguindo.getColumnModel().getColumnCount() > 0) {
            jTableSeguindo.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 430, 230));

        jButtonPararDeSeguir.setText("Parar de Seguir");
        jButtonPararDeSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararDeSeguirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPararDeSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        javax.swing.GroupLayout jTelaSeguindoLayout = new javax.swing.GroupLayout(jTelaSeguindo);
        jTelaSeguindo.setLayout(jTelaSeguindoLayout);
        jTelaSeguindoLayout.setHorizontalGroup(
            jTelaSeguindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        jTelaSeguindoLayout.setVerticalGroup(
            jTelaSeguindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        jTetaPrincipal.add(jTelaSeguindo, "jTelaSeguindo");

        jTelaNovosSeguindo.setBackground(new java.awt.Color(51, 51, 51));
        jTelaNovosSeguindo.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeuPerfil1.setText("Meu Perfil");
        jButtonMeuPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfil1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonMeuPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        jButtonSeguir.setText("Seguir");
        jButtonSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeguirActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 70, -1));

        jTableNovosSeguindo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pessoas para seguir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNovosSeguindo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNovosSeguindoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableNovosSeguindo);
        if (jTableNovosSeguindo.getColumnModel().getColumnCount() > 0) {
            jTableNovosSeguindo.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 260));

        javax.swing.GroupLayout jTelaNovosSeguindoLayout = new javax.swing.GroupLayout(jTelaNovosSeguindo);
        jTelaNovosSeguindo.setLayout(jTelaNovosSeguindoLayout);
        jTelaNovosSeguindoLayout.setHorizontalGroup(
            jTelaNovosSeguindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaNovosSeguindoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTelaNovosSeguindoLayout.setVerticalGroup(
            jTelaNovosSeguindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTelaNovosSeguindoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTetaPrincipal.add(jTelaNovosSeguindo, "jTelaNovosSeguindo");

        jTelaSeguidores.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMeuPerfil2.setText("Meu Perfil");
        jButtonMeuPerfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfil2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonMeuPerfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        jTableSeguidores.setBackground(new java.awt.Color(153, 153, 153));
        jTableSeguidores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTableSeguidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Seguidores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableSeguidores);
        if (jTableSeguidores.getColumnModel().getColumnCount() > 0) {
            jTableSeguidores.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 410, 290));

        javax.swing.GroupLayout jTelaSeguidoresLayout = new javax.swing.GroupLayout(jTelaSeguidores);
        jTelaSeguidores.setLayout(jTelaSeguidoresLayout);
        jTelaSeguidoresLayout.setHorizontalGroup(
            jTelaSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaSeguidoresLayout.setVerticalGroup(
            jTelaSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTetaPrincipal.add(jTelaSeguidores, "jTelaSeguidores");

        getContentPane().add(jTetaPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed

        limpaCadastro();
        jLabelAvisoLogin.setText("");
        mostraCard("jTelaCadastro");

    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        try {
            Pessoa pessoa = listaSocial.getPessoaPorEmail(jTextFieldLoginEmail.getText());
            perfilLogado(pessoa);
            atualizaSeguindo();
            mostraCard("jTelaPerfil");
        } catch (Exception e) {
            jLabelAvisoLogin.setText("Email nao encontrado");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonCadastrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrar3ActionPerformed

        if (!listaSocial.getTemPessoaPorEmail(jTextFieldCadastroEmail.getText())) {
            Pessoa pessoa = new Pessoa(
                    jTextFieldCadastroNome.getText(),
                    jTextFieldCadastroEmail.getText(),
                    jFormattedTextFieldDataNasc.getText());
            listaSocial.seguirPessoa(pessoa);
          
            mostraCard("jTelaLogin");
            jTextFieldLoginEmail.setText(jTextFieldCadastroEmail.getText());
            limpaCadastro();
            jLabelAvisoLogin.setText("");
        } else {
            jLabelCadastroNotifica.setText("Email ja Cadastrado");
        }
    }//GEN-LAST:event_jButtonCadastrar3ActionPerformed

    private void jButtonLogautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogautActionPerformed
        mostraCard("jTelaLogin");
        jLabelAvisoLogin.setText("");

    }//GEN-LAST:event_jButtonLogautActionPerformed

    private void jButtonSairCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadastroActionPerformed
        mostraCard("jTelaLogin");
        limpaCadastro();
        jLabelAvisoLogin.setText("");

    }//GEN-LAST:event_jButtonSairCadastroActionPerformed

    private void jButtonSeguindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeguindoActionPerformed
        atualizaSeguindo();
        mostraCard("jTelaSeguindo");
    }//GEN-LAST:event_jButtonSeguindoActionPerformed

    private void jTableSeguindoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSeguindoMouseClicked
        jButtonPararDeSeguir.setVisible(true);
    }//GEN-LAST:event_jTableSeguindoMouseClicked

    private void jButtonMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfilActionPerformed
        mostraCard("jTelaPerfil");
        atualizaSeguindo();
    }//GEN-LAST:event_jButtonMeuPerfilActionPerformed

    private void jButtonSeguirNovosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeguirNovosActionPerformed
        mostraCard("jTelaNovosSeguindo");
        atualizaNovosSeguindo();
        jButtonSeguir.setVisible(false);
    }//GEN-LAST:event_jButtonSeguirNovosActionPerformed

    private void jButtonMeuPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfil1ActionPerformed
        mostraCard("jTelaPerfil");
        atualizaSeguindo();
    }//GEN-LAST:event_jButtonMeuPerfil1ActionPerformed

    private void jButtonSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeguirActionPerformed
        try {

            Pessoa pessoa = nSeguindo.get(jTableNovosSeguindo.getSelectedRow());
            int opc = JOptionPane.showConfirmDialog(null,
                    "Adicionar " + pessoa.getNome()
                    + " email" + pessoa.getEmail() + "?");
            if (opc == JOptionPane.YES_OPTION) {
                Pessoa aux = logada;
                logada.adicionarSeguindo(pessoa);
                listaSocial.atualizaPessoa(aux, logada);
                atualizaNovosSeguindo();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonSeguirActionPerformed

    private void jTableNovosSeguindoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNovosSeguindoMouseClicked
        jButtonSeguir.setVisible(true);
    }//GEN-LAST:event_jTableNovosSeguindoMouseClicked

    private void SeguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguidoresActionPerformed
        mostraCard("jTelaSeguidores");
        atualizaSeguidores();
    }//GEN-LAST:event_SeguidoresActionPerformed

    private void jButtonMeuPerfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfil2ActionPerformed
        mostraCard("jTelaPerfil");
        atualizaSeguindo();
    }//GEN-LAST:event_jButtonMeuPerfil2ActionPerformed

    private void jButtonPararDeSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararDeSeguirActionPerformed
        try {

            Pessoa pessoa = seguindo.get(jTableSeguindo.getSelectedRow());
            int opc = JOptionPane.showConfirmDialog(null,
                    "Parar de Seguir: " + pessoa.getNome()
                    + " email :" + pessoa.getEmail() + "?");
            if (opc == JOptionPane.YES_OPTION) {
                Pessoa aux = logada;
                logada.removerSeguindo(pessoa);
                listaSocial.atualizaPessoa(aux, logada);
                atualizaSeguindo();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButtonPararDeSeguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Seguidores;
    private javax.swing.JButton jButtonCadastrar3;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonLogaut;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonMeuPerfil;
    private javax.swing.JButton jButtonMeuPerfil1;
    private javax.swing.JButton jButtonMeuPerfil2;
    private javax.swing.JButton jButtonPararDeSeguir;
    private javax.swing.JButton jButtonSairCadastro;
    private javax.swing.JButton jButtonSeguindo;
    private javax.swing.JButton jButtonSeguir;
    private javax.swing.JButton jButtonSeguirNovos;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAvisoLogin;
    private javax.swing.JLabel jLabelCadastroNotifica;
    private javax.swing.JLabel jLabelPerfilEmail;
    private javax.swing.JLabel jLabelPerfilNascimento;
    private javax.swing.JLabel jLabelPerfilNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableNovosSeguindo;
    private javax.swing.JTable jTableSeguidores;
    private javax.swing.JTable jTableSeguindo;
    private javax.swing.JPanel jTelaCadastro;
    private javax.swing.JPanel jTelaLogin;
    private javax.swing.JPanel jTelaNovosSeguindo;
    private javax.swing.JPanel jTelaPerfil;
    private javax.swing.JPanel jTelaSeguidores;
    private javax.swing.JPanel jTelaSeguindo;
    private javax.swing.JPanel jTetaPrincipal;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldCadastroNome;
    private javax.swing.JTextField jTextFieldLoginEmail;
    // End of variables declaration//GEN-END:variables
}
